Fix compilation for zig master
Vexu/bog pull request #19
Opened 2021-09-04 07:33 UTC by iddev5

This PR fixes bog's compilation for Zig master 0.9.0-dev.897+81e2034d4 (os reorganization).

Additional changes:
- AutoIndentingStream taken from std/zig/render.zig
- Zig's std.math.sqrt() no longer works on i64. Bog's std lib casts it the argument into a u64.

2021-09-04 09:17 UTC, Vexu requested changes
Few tweaks needed but otherwise looks good.

2021-09-04 09:17 UTC, Vexu commented on src/tokenizer.zig
> +    pub fn string(id: std.meta.TagType(Id)) []const u8 {
Same here.

2021-09-04 09:17 UTC, Vexu commented on src/value.zig
> +            else => if (a.* != @as(std.meta.TagType(@TypeOf(b.*)), b.*)) return false,
And here.

2021-09-04 09:17 UTC, Vexu commented on src/value.zig
> +            .map => |_| @panic("TODO eql for maps"),
```suggestion
            .map => @panic("TODO eql for maps"),
```

2021-09-04 09:17 UTC, Vexu commented on src/vm.zig
> +                    const copy: Value = if (needNum(lhs, rhs)) .{ .num = asNum(lhs) + asNum(rhs) } else .{ .int = lhs.int + rhs.int };
Add commas to all of these to avoid `zig fmt` creating long lines.

2021-09-04 12:44 UTC, iddev5 commented
Made the changes, hope everything is cleared! Let me know if something is off

2021-09-05 14:30 UTC, merged

2021-09-05 14:30 UTC, Vexu commented
Thanks!